### ISSUE TITLE
I'm afraid this library will offend some clients

### ISSUE THREAD

**Issue by quentin-sommer** [thejameskyle/gender-regex#1]
Can I use this library for binary genders? I'm afraid my client will feel offended by this. 

Perhaps we could restructure this using a tool like `lerna` and a root package `gender-regex` with plugins `gender-regex-{denominator}`? We could even generate them automatically from some Twitter accounts or Tumblr blogs :smile:

**Comment by thejameskyle** [comment]
the internet is so fast to disappoint me
